# Generated by Django 2.2.5 on 2019-10-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(3, 3), (5, 5), (4, 4), (2, 2), (1, 1)])),
                ('review', models.CharField(max_length=500)),
            ],
        ),
    ]
